name: CI Pipeline Failure Demo

# on:                          # Comment Out the push trigger to avoid running this workflow on every push 
#   push:
#     branches:                   
#       - main

on:
  workflow_dispatch:           # This allows you to trigger the workflow manually from the GitHub Actions tab in your repository.
                               # It won't run automatically on every push to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: cicd/github-actions/pipeline-failure
        run: npm install

      - name: Run App
        working-directory: cicd/github-actions/pipeline-failure
        run: node index.js