name: Runner Down Demo

# on:                          # Comment Out the push trigger to avoid running this workflow on every push 
#   push:
#     branches:                   
#       - main

on:
  workflow_dispatch:           # This allows you to trigger the workflow manually from the GitHub Actions tab in your repository.
                               # It won't run automatically on every push to the main branch.

jobs:
  runner-check:
    runs-on: self-hosted   #  Requires your runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "Runner is working fine 🚀"

      - name: Simulate Work
        run: |
          echo "Running job..."
          sleep 5
          echo "Done!"